### PR TITLE
Add logger and expose docker socket in girder container

### PR DESCRIPTION
**Pull request by Xarthisius**
Necessary bits for testing:
1. Logs from running instances -- https://github.com/whole-tale/girder_wholetale/pull/557
2. Dynamic image info creation:
   - https://github.com/whole-tale/girder/pull/16
   - https://github.com/whole-tale/girder_wholetale/pull/558
   - https://github.com/whole-tale/gwvolman/pull/183

Exercise left to the reviewer: how to get a local GID of the `docker` group  dynamically...

### CODE REVIEW

**Comment by craig-willis** [comment]
If I don't mount mount the host /tmp dir into the Girder service, run_r2d fails with the below error but the tag is still generated based, but based on the error output.
```
[2022-10-18 15:24:37,739] INFO: [Repo2Docker] Looking for /wholetale/repo2docker_config in /
[2022-10-18 15:24:37,743] INFO: [Repo2Docker] Loaded config file: /wholetale/repo2docker_config.py
[2022-10-18 15:24:38,010] INFO: Picked Git content provider.
[2022-10-18 15:24:38,017] INFO: fatal: repository '//tmp/tmpo5yvdhtd' does not exist
[2022-10-18 15:24:38,017] INFO: Traceback (most recent call last):
[2022-10-18 15:24:38,017] INFO: File "/usr/lib/python3.9/site-packages/repo2docker/contentproviders/git.py", line 33, in fetch
[2022-10-18 15:24:38,017] INFO: for line in execute_cmd(cmd, capture=yield_output):
[2022-10-18 15:24:38,017] INFO: File "/usr/lib/python3.9/site-packages/repo2docker/utils.py", line 29, in execute_cmd
[2022-10-18 15:24:38,018] INFO: raise subprocess.CalledProcessError(ret, cmd)
[2022-10-18 15:24:38,018] INFO: subprocess.CalledProcessError: Command '['git', 'clone', '--depth', '1', '//tmp/tmpo5yvdhtd', '/tmp/repo2dockermqnkhay2']' returned non-zero exit status 128.
[2022-10-18 15:24:38,018] INFO: The above exception was the direct cause of the following exception:
[2022-10-18 15:24:38,019] INFO: Traceback (most recent call last):
[2022-10-18 15:24:38,019] INFO: File "/usr/bin/jupyter-repo2docker", line 8, in <module>
[2022-10-18 15:24:38,019] INFO: sys.exit(main())
[2022-10-18 15:24:38,019] INFO: File "/usr/lib/python3.9/site-packages/repo2docker/__main__.py", line 443, in main
[2022-10-18 15:24:38,019] INFO: r2d.start()
[2022-10-18 15:24:38,019] INFO: File "/usr/lib/python3.9/site-packages/repo2docker/app.py", line 851, in start
[2022-10-18 15:24:38,020] INFO: self.build()
[2022-10-18 15:24:38,020] INFO: File "/usr/lib/python3.9/site-packages/repo2docker/app.py", line 752, in build
[2022-10-18 15:24:38,020] INFO: self.fetch(self.repo, self.ref, checkout_path)
[2022-10-18 15:24:38,020] INFO: File "/usr/lib/python3.9/site-packages/repo2docker/app.py", line 481, in fetch
[2022-10-18 15:24:38,020] INFO: for log_line in picked_content_provider.fetch(
[2022-10-18 15:24:38,020] INFO: File "/usr/lib/python3.9/site-packages/repo2docker/contentproviders/git.py", line 41, in fetch
[2022-10-18 15:24:38,020] INFO: raise ContentProviderException(msg) from e
[2022-10-18 15:24:38,020] INFO: repo2docker.contentproviders.base.ContentProviderException: Failed to clone repository from //tmp/tmpo5yvdhtd.
```

Mounting tmp into the girder container solves this.

**Comment by craig-willis** [comment]
Because run_r2d assumes `/host/tmp` as the shared mountpoint, I think we need:

```
    volumes:
...
      - /tmp:/host/tmp
    environment:
...
      - HOSTDIR=/host
```

Without these, get_tag fails for me because it run_r2d can't find the workspace.

**Comment by Xarthisius** [comment]
> Because run_r2d assumes `/host/tmp` as the shared mountpoint, I think we need:
> 
> ```
>     volumes:
> ...
>       - /tmp:/host/tmp
>     environment:
> ...
>       - HOSTDIR=/host
> ```
> 
> Without these, get_tag fails for me because it run_r2d can't find the workspace.

If that's happening it's a bug. What's the point in having a HOSTDIR env var if it only works with one value?

**Comment by Xarthisius** [comment]
> Because run_r2d assumes `/host/tmp` as the shared mountpoint.

Fix0red all occurrences of `/host` (turned out there were quite a few...) in https://github.com/whole-tale/gwvolman/pull/183/commits/7ce6447f0e9a6448b3f7e639666f526bf9fe991d

**Review by craig-willis — APPROVED** [review]

**Review by bodom0015 — APPROVED** [review]
LGTM :+1: the defaults worked fine here.. there was no reason to update the Docker GID or anything, but maybe the defaults here "just work" for Ubuntu?

One way to get the docker GID might be something like this?
Exec into the girder_wholetale container and run `getent group` to find the docker group, and then use cut to pull out the GID:
```
docker exec -it \
    $(docker ps -f name=girder -q) \
    getent group | grep docker | cut -d ":" -f 3
```

**Pull request merged**
