### PR TITLE
Add versioning plugin

### PR DESCRIPTION
**Pull request by Xarthisius**
Setup modification necessary to enable versioning support

### Corresponding PRs:

* https://github.com/whole-tale/girderfs/pull/13
* https://github.com/whole-tale/girder_wt_data_manager/pull/44
* https://github.com/whole-tale/gwvolman/pull/113

### Update
Now also needs https://github.com/whole-tale/wt_versioning/pull/12

### CODE REVIEW

**Comment by bodom0015** [comment]
Running into an HTTP 400 Bad Request with `make dev` here.. Anyone else seeing this behavior as well?
```
Waiting for Girder to restart
Waiting for Girder to restart
Waiting for Girder to restart
Waiting for Girder to restart
Waiting for Girder to restart
Setting up Plugin
Traceback (most recent call last):
  File "./setup_girder.py", line 139, in <module>
    r.raise_for_status()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://girder.local.wholetale.org/api/v1/system/setting?list=%5B%7B%22value%22%3A+%22https%3A%2F%2Fdashboard.local.wholetale.org%2Chttp%3A%2F%2Flocalhost%3A4200%2Chttps%3A%2F%2Flegacy.local.wholetale.org%22%2C+%22key%22%3A+%22core.cors.allow_origin%22%7D%2C+%7B%22value%22%3A+%22Accept-Encoding%2C+Authorization%2C+Content-Disposition%2C+Set-Cookie%2C+Content-Type%2C+Cookie%2C+Girder-Authorization%2C+Girder-Token%2C+X-Requested-With%2C+X-Forwarded-Server%2C+X-Forwarded-For%2C+X-Forwarded-Host%2C+Remote-Addr%2C+Cache-Control%22%2C+%22key%22%3A+%22core.cors.allow_headers%22%7D%2C+%7B%22value%22%3A+%22http%3A%2F%2Fgirder%3A8080%2Fapi%2Fv1%22%2C+%22key%22%3A+%22worker.api_url%22%7D%2C+%7B%22value%22%3A+%22redis%3A%2F%2Fredis%2F%22%2C+%22key%22%3A+%22worker.broker%22%7D%2C+%7B%22value%22%3A+%22redis%3A%2F%2Fredis%2F%22%2C+%22key%22%3A+%22worker.backend%22%7D%2C+%7B%22value%22%3A+%227a299ca5-eb92-48e7-8cb8-9f379ed793e1%22%2C+%22key%22%3A+%22oauth.globus_client_id%22%7D%2C+%7B%22value%22%3A+%22WCCoAivf513dDIEOcbE9QMQoeKPQh9%2B0zF58RFG497o%3D%22%2C+%22key%22%3A+%22oauth.globus_client_secret%22%7D%2C+%7B%22value%22%3A+%22APP-B6D26KCPIQSPMAYO%22%2C+%22key%22%3A+%22oauth.orcid_client_id%22%7D%2C+%7B%22value%22%3A+%2264a94f0a-93fa-43c4-8a24-a07b0e705e82%22%2C+%22key%22%3A+%22oauth.orcid_client_secret%22%7D%2C+%7B%22value%22%3A+%5B%22globus%22%5D%2C+%22key%22%3A+%22oauth.providers_enabled%22%7D%2C+%7B%22value%22%3A+%22%2Fopt%2Fglobusconnectpersonal%22%2C+%22key%22%3A+%22dm.globus_gc_dir%22%7D%2C+%7B%22value%22%3A+%5B%22dev2.dataverse.org%22%2C+%22demo.dataverse.org%22%5D%2C+%22key%22%3A+%22wholetale.dataverse_extra_hosts%22%7D%2C+%7B%22value%22%3A+%22%2Ftmp%2Fdata%2Fps%22%2C+%22key%22%3A+%22dm.private_storage_path%22%7D%2C+%7B%22value%22%3A+%22%2Ftmp%2Fdata%2Fhomes%22%2C+%22key%22%3A+%22wthome.homedir_root%22%7D%2C+%7B%22value%22%3A+%22%2Ftmp%2Fdata%2Fworkspaces%22%2C+%22key%22%3A+%22wthome.taledir_root%22%7D%2C+%7B%22value%22%3A+%22%2Ftmp%2Fdata%2Fruns%22%2C+%22key%22%3A+%22wtversioning.runs_root%22%7D%2C+%7B%22value%22%3A+%22%2Ftmp%2Fdata%2Fversions%22%2C+%22key%22%3A+%22wtversioning.versions_root%22%7D%5D
Makefile:64: recipe for target 'dev' failed
make: *** [dev] Error 1

```

URL decoding that long string above, it looks like there might have been some extra whitespace added to wherever this JSON was encoded from. Notice the extra `+` symbols throughout:
```
https://girder.local.wholetale.org/api/v1/system/setting?list=[{"value":+"https://dashboard.local.wholetale.org,http://localhost:4200,https://legacy.local.wholetale.org",+"key":+"core.cors.allow_origin"},+{"value":+"Accept-Encoding,+Authorization,+Content-Disposition,+Set-Cookie,+Content-Type,+Cookie,+Girder-Authorization,+Girder-Token,+X-Requested-With,+X-Forwarded-Server,+X-Forwarded-For,+X-Forwarded-Host,+Remote-Addr,+Cache-Control",+"key":+"core.cors.allow_headers"},+{"value":+"http://girder:8080/api/v1",+"key":+"worker.api_url"},+{"value":+"redis://redis/",+"key":+"worker.broker"},+{"value":+"redis://redis/",+"key":+"worker.backend"},+{"value":+"7a299ca5-eb92-48e7-8cb8-9f379ed793e1",+"key":+"oauth.globus_client_id"},+{"value":+"WCCoAivf513dDIEOcbE9QMQoeKPQh9+0zF58RFG497o=",+"key":+"oauth.globus_client_secret"},+{"value":+"APP-B6D26KCPIQSPMAYO",+"key":+"oauth.orcid_client_id"},+{"value":+"64a94f0a-93fa-43c4-8a24-a07b0e705e82",+"key":+"oauth.orcid_client_secret"},+{"value":+["globus"],+"key":+"oauth.providers_enabled"},+{"value":+"/opt/globusconnectpersonal",+"key":+"dm.globus_gc_dir"},+{"value":+["dev2.dataverse.org",+"demo.dataverse.org"],+"key":+"wholetale.dataverse_extra_hosts"},+{"value":+"/tmp/data/ps",+"key":+"dm.private_storage_path"},+{"value":+"/tmp/data/homes",+"key":+"wthome.homedir_root"},+{"value":+"/tmp/data/workspaces",+"key":+"wthome.taledir_root"},+{"value":+"/tmp/data/runs",+"key":+"wtversioning.runs_root"},+{"value":+"/tmp/data/versions",+"key":+"wtversioning.versions_root"}]
```

Removing these spaces should resolve the problem

**Comment by Xarthisius** [comment]
> Removing these spaces should resolve the problem

Spaces are fine. Can you make the following modification to your deployment:

```diff
diff --git a/setup_girder.py b/setup_girder.py
index c6d99ae..3036ae4 100755
--- a/setup_girder.py
+++ b/setup_girder.py
@@ -1,4 +1,4 @@
-#!/usr/bin/env python
+#!/usr/bin/env python3
 import json
 import requests
 import time
@@ -136,7 +136,13 @@ settings = [
 r = requests.put(
     api_url + "/system/setting", headers=headers, params={"list": json.dumps(settings)}
 )
-r.raise_for_status()
+try:
+    r.raise_for_status()
+except requests.exceptions.HTTPError:
+    if r.status_code >= 400 and r.status_code < 500:
+        print(f"Request died with {r.status_code}: {r.reason}")
+        print(f"Returned: {r.text}")
+    raise
 
 print("Create a Jupyter image")
 i_params = {
```

and see what's girder complaining about? You should get output similar to:

```
Setting up Plugin
Request died with 400: Bad Request
Returned: {"field": "key", "message": "Invalid setting key \"wtversionin.runs_root\".", "type": "validation"}
Traceback (most recent call last):
  File "./setup_girder.py", line 140, in <module>
    r.raise_for_status()
  File "/home/xarth/.local/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://girder.local.wholetale.org/api/v1/system/setting?list=%5B%7B%22key%22%3A+%22core.cors.allow_origin%22%2C+%22value%22%3A+%22https%3A%2F%2Fdashboard.local.wholetale.org%2Chttp%3A%2F%2Flocalhost%3A4200%2Chttps%3A%2F%2Flegacy.local.wholetale.org%22%7D%2C+%7B%22key%22%3A+%22core.cors.allow_headers%22%2C+%22value%22%3A+%22Accept-Encoding%2C+Authorization%2C+Content-Disposition%2C+Set-Cookie%2C+Content-Type%2C+Cookie%2C+Girder-Authorization%2C+Girder-Token%2C+X-Requested-With%2C+X-Forwarded-Server%2C+X-Forwarded-For%2C+X-Forwarded-Host%2C+Remote-Addr%2C+Cache-Control%22%7D%2C+%7B%22key%22%3A+%22worker.api_url%22%2C+%22value%22%3A+%22http%3A%2F%2Fgirder%3A8080%2Fapi%2Fv1%22%7D%2C+%7B%22key%22%3A+%22worker.broker%22%2C+%22value%22%3A+%22redis%3A%2F%2Fredis%2F%22%7D%2C+%7B%22key%22%3A+%22worker.backend%22%2C+%22value%22%3A+%22redis%3A%2F%2Fredis%2F%22%7D%2C+%7B%22key%22%3A+%22oauth.globus_client_id%22%2C+%22value%22%3A+%220baa7c04-1ff6-4cf5-82b3-00dd47e828d9%22%7D%2C+%7B%22key%22%3A+%22oauth.globus_client_secret%22%2C+%22value%22%3A+%227G7Yc%2BDWev9h0QFPdCIrAotmoSU2Wc3626%2B60WNCpk0%3D%22%7D%2C+%7B%22key%22%3A+%22oauth.orcid_client_id%22%2C+%22value%22%3A+%22APP-B6D26KCPIQSPMAYO%22%7D%2C+%7B%22key%22%3A+%22oauth.orcid_client_secret%22%2C+%22value%22%3A+%2264a94f0a-93fa-43c4-8a24-a07b0e705e82%22%7D%2C+%7B%22key%22%3A+%22oauth.providers_enabled%22%2C+%22value%22%3A+%5B%22globus%22%5D%7D%2C+%7B%22key%22%3A+%22dm.globus_gc_dir%22%2C+%22value%22%3A+%22%2Fopt%2Fglobusconnectpersonal%22%7D%2C+%7B%22key%22%3A+%22wholetale.dataverse_extra_hosts%22%2C+%22value%22%3A+%5B%22dev2.dataverse.org%22%2C+%22demo.dataverse.org%22%5D%7D%2C+%7B%22key%22%3A+%22dm.private_storage_path%22%2C+%22value%22%3A+%22%2Ftmp%2Fdata%2Fps%22%7D%2C+%7B%22key%22%3A+%22wthome.homedir_root%22%2C+%22value%22%3A+%22%2Ftmp%2Fdata%2Fhomes%22%7D%2C+%7B%22key%22%3A+%22wthome.taledir_root%22%2C+%22value%22%3A+%22%2Ftmp%2Fdata%2Fworkspaces%22%7D%2C+%7B%22key%22%3A+%22wtversionin.runs_root%22%2C+%22value%22%3A+%22%2Ftmp%2Fdata%2Fruns%22%7D%2C+%7B%22key%22%3A+%22wtversioning.versions_root%22%2C+%22value%22%3A+%22%2Ftmp%2Fdata%2Fversions%22%7D%5D
```

**Comment by Xarthisius** [comment]
Also looking at the girder container logs for possible tracebacks could shed some light.

**Comment by bodom0015** [comment]
Ahh, yeah I hadn't checked girder and apparently I forgot to check out all of the associated PRs.. 

Thank you, I will give it another try :+1:

EDIT: Something about that f-string code is giving a syntax error:
```

./setup_girder.py
  File "./setup_girder.py", line 143
    print(f"Request died with {r.status_code}: {r.reason}")
                                                         ^
SyntaxError: invalid syntax
Makefile:64: recipe for target 'dev' failed
```

Changing these lines to use the old `%s` format method seemed to workaround things for now: `print('Request died with %s: %s' % (r.status_code, r.reason))`

EDIT 2: It's working now! :+1: It turns out that I was missing a `git pull origin master` on all of the other repos. `girder` and `wholetale` specifically were missing quite a few changes that were likely needed... I'll need to double-check to make sure that the `pull-upstream.sh` includes all of these repos, as well as the new ones that have been added lately

**Comment by bodom0015** [comment]
I think there is something off with the `force=false` case.

My first `POST /version` from Girder's Swagger UI worked just fine, but attempting to create subsequent versions yields a `500 Internal Server Error`:
```
https://girder.local.wholetale.org/api/v1/version?taleId=5f887d8e81d63263a60a65b9&force=false

{
  "message": "FileNotFoundError: FileNotFoundError(2, 'No such file or directory')",
  "trace": [
    "<FrameSummary file /girder/girder/api/rest.py, line 630 in endpointDecorator>",
    "<FrameSummary file /girder/girder/api/rest.py, line 1224 in POST>",
    "<FrameSummary file /girder/girder/api/rest.py, line 967 in handleRoute>",
    "<FrameSummary file /girder/girder/api/access.py, line 63 in wrapped>",
    "<FrameSummary file /girder/girder/api/rest.py, line 445 in wrapped>",
    "<FrameSummary file /girder/girder/api/describe.py, line 709 in wrapped>",
    "<FrameSummary file /girder/plugins/wt_versioning/server/resources/version.py, line 132 in create>",
    "<FrameSummary file /girder/plugins/wt_versioning/server/resources/version.py, line 274 in _create>",
    "<FrameSummary file /usr/lib/python3.7/shutil.py, line 482 in rmtree>",
    "<FrameSummary file /usr/lib/python3.7/shutil.py, line 480 in rmtree>"
  ],
  "type": "internal"
}
```

If I set `force=true`, then it works as intended:
```
https://girder.local.wholetale.org/api/v1/version?taleId=5f887d8e81d63263a60a65b9&force=true

{
  "_accessLevel": 2,
  "_id": "5f888ca981d63263a60a65d9",
  "_modelType": "folder",
  "baseParentId": "5f887d3b81d63263a60a65a6",
  "baseParentType": "collection",
  "created": "2020-10-15T17:53:45.731120+00:00",
  "creatorId": "5f887c6a81d63263a60a657f",
  "description": "",
  "isMapping": true,
  "name": "Thu Oct 15 17:53:45 2020",
  "parentCollection": "folder",
  "parentId": "5f887d8e81d63263a60a65ba",
  "public": false,
  "size": 0,
  "updated": "2020-10-15T17:53:45.731120+00:00"
}
```

Anyone else seeing this as well?

______________________

Also noting some slight divergences from typical REST patterns:
* Utilize top-level resource for listing collections: e.g. `GET /version` instead of `GET /version/list`
* `GET` should not modify resources: e.g. `PUT /version/{id}` instead of `GET /version/{id}/rename`
* No need to include a redundant "get" in endpoint path: e.g. `GET /version/root` instead of `GET /version/getRoot`
* `HEAD` can be used to check for existence of resource without returning the full resource - some frameworks can reuse the same code/handler in this case too, just returning `204 No Content` instead of `200 OK`

**Comment by hategan** [comment]
Hmm. So there's a double rollback there which removes the new directory, one in _create() and one in snapshot(), so the outer one (_create()) will always fail. That also happens to obscure the exception that triggers it all.

On the REST patterns, yeah, makes sense. I'll change those. I'm guessing the REST API isn't used anywhere yet so I can change them without much coordination?

**Comment by bodom0015** [comment]
@hategan unless Girder relies on that API somewhere internally or in a plugin, then you should be able to change them without consequence

I haven't written the API client for the UI yet (I was working on the first steps toward that when I ran into the `force=false` thing), so there shouldn't be any issue there if changes are made/needed

**Review by ThomasThelen — APPROVED** [review]
I've deployed this a few times without issue; LGTM

**Review by craig-willis — APPROVED** [review]

**Pull request merged**
